name: real_estate
description: 'A new Flutter project.'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # utils
  gap: ^3.0.0

  # state management
  flutter_hooks: ^0.18.6
  iconsax: ^0.0.8

  # animations
  animations: ^2.0.7
  flutter_animate: ^4.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/Euclid-Regular.ttf
          weight: 400
        - asset: assets/fonts/Euclid-Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid-SemiBold.ttf
          weight: 600
